export type IconFamily = "classic" | "sharp" | "duotone";
export type IconPrefix = "fas" | "far" | "fal" | "fat" | "fad" | "fab" | "fak" | "fass" | "fasr" | "fasl" ;
export type CssStyleClass = "fa-solid" | "fa-regular" | "fa-light" | "fa-thin" | "fa-duotone" | "fa-brands" ;
export type IconStyle = "solid" | "regular" | "light" | "thin" | "duotone" | "brands" ;
export type IconPathData = string | string[]

export interface IconLookup {
  prefix: IconPrefix;
  // IconName is defined in the code that will be generated at build time and bundled with this file.
  iconName: IconName;
}

export interface IconDefinition extends IconLookup {
  icon: [
    number, // width
    number, // height
    string[], // ligatures
    string, // unicode
    IconPathData // svgPathData
  ];
}

export interface IconPack {
  [key: string]: IconDefinition;
}

export type IconName = 'cc-visa' | 
  'ups' | 
  'mailchimp' | 
  'vimeo-v' | 
  'square-instagram' | 
  'instagram-square' | 
  'square-snapchat' | 
  'snapchat-square' | 
  'google-plus-g' | 
  'google-plus' | 
  'google' | 
  'linkedin-in' | 
  'cc-apple-pay' | 
  'square-twitter' | 
  'twitter-square' | 
  'app-store' | 
  'cc-mastercard' | 
  'square-youtube' | 
  'youtube-square' | 
  'discord' | 
  'app-store-ios' | 
  'cc-discover' | 
  'ebay' | 
  'square-vimeo' | 
  'vimeo-square' | 
  'apple' | 
  'apple-pay' | 
  'cc-paypal' | 
  'cc-stripe' | 
  'bitcoin' | 
  'square-pinterest' | 
  'pinterest-square' | 
  'facebook-f' | 
  'square-google-plus' | 
  'google-plus-square' | 
  'wpforms' | 
  'usps' | 
  'audible' | 
  'tiktok' | 
  'square-facebook' | 
  'facebook-square' | 
  'linkedin' | 
  'vimeo' | 
  'cc-amazon-pay' | 
  'instagram' | 
  'facebook' | 
  'whatsapp' | 
  'bluetooth' | 
  'cc-diners-club' | 
  'pinterest-p' | 
  'cc-jcb' | 
  'snapchat' | 
  'snapchat-ghost' | 
  'cc-amex' | 
  'youtube' | 
  'twitter' | 
  'pinterest' | 
  'square-whatsapp' | 
  'whatsapp-square' | 
  'usb' | 
  'google-pay' | 
  'circle-chevron-right' | 
  'chevron-circle-right' | 
  'trash-can' | 
  'trash-alt' | 
  'message' | 
  'comment-alt' | 
  'calendar-days' | 
  'calendar-alt' | 
  'sort-down' | 
  'sort-desc' | 
  'right-from-bracket' | 
  'sign-out-alt' | 
  'chevrons-up' | 
  'chevron-double-up' | 
  'angles-down' | 
  'angle-double-down' | 
  'location-plus' | 
  'map-marker-plus' | 
  'chevrons-left' | 
  'chevron-double-left' | 
  'circle-heart' | 
  'heart-circle' | 
  'address-book' | 
  'contact-book' | 
  'pencil' | 
  'pencil-alt' | 
  'backward' | 
  'caret-right' | 
  'user-check' | 
  'box-archive' | 
  'archive' | 
  'circle-caret-down' | 
  'caret-circle-down' | 
  'gift-card' | 
  'earth-africa' | 
  'globe-africa' | 
  'tablet-screen-button' | 
  'tablet-alt' | 
  'gavel' | 
  'legal' | 
  'bars' | 
  'navicon' | 
  'caret-left' | 
  'circle-exclamation' | 
  'exclamation-circle' | 
  'arrow-right-from-bracket' | 
  'sign-out' | 
  'circle-chevron-down' | 
  'chevron-circle-down' | 
  'compress' | 
  'asterisk' | 
  'square-check' | 
  'check-square' | 
  'list' | 
  'list-squares' | 
  'up-to-line' | 
  'arrow-alt-to-top' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'bag-shopping' | 
  'shopping-bag' | 
  'arrow-down-z-a' | 
  'sort-alpha-desc' | 
  'sort-alpha-down-alt' | 
  'chevron-up' | 
  'stopwatch' | 
  'alarm-clock' | 
  'money-bill' | 
  'bookmark' | 
  'folder' | 
  'folder-blank' | 
  'file-waveform' | 
  'file-medical-alt' | 
  'user' | 
  'globe' | 
  'money-bill-wave' | 
  'star' | 
  'charging-station' | 
  'arrow-right-to-bracket' | 
  'sign-in' | 
  'server' | 
  'right-to-bracket' | 
  'sign-in-alt' | 
  'books' | 
  'user-group' | 
  'user-friends' | 
  'arrow-up-a-z' | 
  'sort-alpha-up' | 
  'play-pause' | 
  'square-chevron-down' | 
  'chevron-square-down' | 
  'comment-plus' | 
  'folder-open' | 
  'user-pen' | 
  'user-edit' | 
  'map-location-dot' | 
  'map-marked-alt' | 
  'gift' | 
  'square-plus' | 
  'plus-square' | 
  'caret-up' | 
  'minimize' | 
  'compress-arrows-alt' | 
  'circle-play' | 
  'play-circle' | 
  'circle-check' | 
  'check-circle' | 
  'marker' | 
  'circle-chevron-up' | 
  'chevron-circle-up' | 
  'pause' | 
  'address-card' | 
  'contact-card' | 
  'vcard' | 
  'circle-caret-up' | 
  'caret-circle-up' | 
  'circle-arrow-left' | 
  'arrow-circle-left' | 
  'envelope-open' | 
  'square' | 
  'down-to-line' | 
  'arrow-alt-to-bottom' | 
  'question' | 
  'money-check' | 
  'code' | 
  'location-pin' | 
  'map-marker' | 
  'arrow-right' | 
  'octagon-plus' | 
  'plus-octagon' | 
  'screwdriver-wrench' | 
  'tools' | 
  'heart' | 
  'mobile-screen-button' | 
  'mobile-alt' | 
  'circle-question' | 
  'question-circle' | 
  'phone-flip' | 
  'phone-alt' | 
  'circle-caret-left' | 
  'caret-circle-left' | 
  'square-chevron-up' | 
  'chevron-square-up' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'file-code' | 
  'shop' | 
  'store-alt' | 
  'floppy-disk' | 
  'save' | 
  'sort-up' | 
  'sort-asc' | 
  'hand-holding-dollar' | 
  'hand-holding-usd' | 
  'phone' | 
  'square-heart' | 
  'heart-square' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'arrow-left' | 
  'table-cells' | 
  'th' | 
  'messages-question' | 
  'comment' | 
  'envelope' | 
  'angles-up' | 
  'angle-double-up' | 
  'circle-info' | 
  'info-circle' | 
  'star-sharp-half-stroke' | 
  'star-sharp-half-alt' | 
  'truck' | 
  'crosshairs' | 
  'arrow-down-a-z' | 
  'sort-alpha-asc' | 
  'sort-alpha-down' | 
  'arrow-rotate-left' | 
  'arrow-left-rotate' | 
  'arrow-rotate-back' | 
  'arrow-rotate-backward' | 
  'undo' | 
  'calendar-plus' | 
  'minus' | 
  'subtract' | 
  'gear' | 
  'cog' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'keyboard' | 
  'caret-down' | 
  'piggy-bank' | 
  'sliders' | 
  'sliders-h' | 
  'map-pin' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'ticket' | 
  'download' | 
  'forward' | 
  'id-card' | 
  'drivers-license' | 
  'calendar-week' | 
  'rotate-right' | 
  'redo-alt' | 
  'rotate-forward' | 
  'truck-pickup' | 
  'upload' | 
  'bolt' | 
  'zap' | 
  'trash-undo' | 
  'trash-arrow-turn-left' | 
  'square-question' | 
  'question-square' | 
  'angle-down' | 
  'thumbs-down' | 
  'arrow-right-long' | 
  'long-arrow-right' | 
  'credit-card' | 
  'credit-card-alt' | 
  'bluetooth' | 
  'bell' | 
  'location-dot' | 
  'map-marker-alt' | 
  'file' | 
  'eraser' | 
  'earth-americas' | 
  'earth' | 
  'earth-america' | 
  'globe-americas' | 
  'star-half' | 
  'link' | 
  'chain' | 
  'magnifying-glass' | 
  'search' | 
  'chevrons-down' | 
  'chevron-double-down' | 
  'location-question' | 
  'map-marker-question' | 
  'receipt' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'square-chevron-right' | 
  'chevron-square-right' | 
  'truck-fast' | 
  'shipping-fast' | 
  'square-chevron-left' | 
  'chevron-square-left' | 
  'copy' | 
  'gun' | 
  'plus' | 
  'add' | 
  'expand' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'store' | 
  'chevron-left' | 
  'chevron-right' | 
  'location-check' | 
  'map-marker-check' | 
  'thumbtack' | 
  'thumb-tack' | 
  'spinner' | 
  'gears' | 
  'cogs' | 
  'circle-chevron-left' | 
  'chevron-circle-left' | 
  'bags-shopping' | 
  'calendar' | 
  'desktop' | 
  'desktop-alt' | 
  'book' | 
  'user-plus' | 
  'check' | 
  'earth-europe' | 
  'globe-europe' | 
  'chevrons-right' | 
  'chevron-double-right' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'circle-caret-right' | 
  'caret-circle-right' | 
  'circle-xmark' | 
  'times-circle' | 
  'xmark-circle' | 
  'gifts' | 
  'earth-asia' | 
  'globe-asia' | 
  'magnifying-glass-plus' | 
  'search-plus' | 
  'thumbs-up' | 
  'file-invoice' | 
  'magnifying-glass-minus' | 
  'search-minus' | 
  'print' | 
  'dollar-sign' | 
  'dollar' | 
  'usd' | 
  'users-gear' | 
  'users-cog' | 
  'barcode' | 
  'notdef' | 
  'circle-chevron-right' | 
  'chevron-circle-right' | 
  'trash-can' | 
  'trash-alt' | 
  'message' | 
  'comment-alt' | 
  'calendar-days' | 
  'calendar-alt' | 
  'sort-down' | 
  'sort-desc' | 
  'right-from-bracket' | 
  'sign-out-alt' | 
  'chevrons-up' | 
  'chevron-double-up' | 
  'angles-down' | 
  'angle-double-down' | 
  'location-plus' | 
  'map-marker-plus' | 
  'chevrons-left' | 
  'chevron-double-left' | 
  'circle-heart' | 
  'heart-circle' | 
  'address-book' | 
  'contact-book' | 
  'pencil' | 
  'pencil-alt' | 
  'backward' | 
  'caret-right' | 
  'user-check' | 
  'box-archive' | 
  'archive' | 
  'circle-caret-down' | 
  'caret-circle-down' | 
  'gift-card' | 
  'earth-africa' | 
  'globe-africa' | 
  'tablet-screen-button' | 
  'tablet-alt' | 
  'gavel' | 
  'legal' | 
  'bars' | 
  'navicon' | 
  'caret-left' | 
  'circle-exclamation' | 
  'exclamation-circle' | 
  'arrow-right-from-bracket' | 
  'sign-out' | 
  'circle-chevron-down' | 
  'chevron-circle-down' | 
  'compress' | 
  'asterisk' | 
  'square-check' | 
  'check-square' | 
  'list' | 
  'list-squares' | 
  'up-to-line' | 
  'arrow-alt-to-top' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'bag-shopping' | 
  'shopping-bag' | 
  'arrow-down-z-a' | 
  'sort-alpha-desc' | 
  'sort-alpha-down-alt' | 
  'chevron-up' | 
  'stopwatch' | 
  'alarm-clock' | 
  'money-bill' | 
  'bookmark' | 
  'folder' | 
  'folder-blank' | 
  'file-waveform' | 
  'file-medical-alt' | 
  'user' | 
  'globe' | 
  'money-bill-wave' | 
  'star' | 
  'charging-station' | 
  'arrow-right-to-bracket' | 
  'sign-in' | 
  'server' | 
  'right-to-bracket' | 
  'sign-in-alt' | 
  'books' | 
  'user-group' | 
  'user-friends' | 
  'arrow-up-a-z' | 
  'sort-alpha-up' | 
  'play-pause' | 
  'square-chevron-down' | 
  'chevron-square-down' | 
  'comment-plus' | 
  'folder-open' | 
  'user-pen' | 
  'user-edit' | 
  'map-location-dot' | 
  'map-marked-alt' | 
  'gift' | 
  'square-plus' | 
  'plus-square' | 
  'caret-up' | 
  'minimize' | 
  'compress-arrows-alt' | 
  'circle-play' | 
  'play-circle' | 
  'circle-check' | 
  'check-circle' | 
  'marker' | 
  'circle-chevron-up' | 
  'chevron-circle-up' | 
  'pause' | 
  'address-card' | 
  'contact-card' | 
  'vcard' | 
  'circle-caret-up' | 
  'caret-circle-up' | 
  'circle-arrow-left' | 
  'arrow-circle-left' | 
  'envelope-open' | 
  'square' | 
  'down-to-line' | 
  'arrow-alt-to-bottom' | 
  'question' | 
  'money-check' | 
  'code' | 
  'location-pin' | 
  'map-marker' | 
  'arrow-right' | 
  'octagon-plus' | 
  'plus-octagon' | 
  'screwdriver-wrench' | 
  'tools' | 
  'heart' | 
  'mobile-screen-button' | 
  'mobile-alt' | 
  'circle-question' | 
  'question-circle' | 
  'phone-flip' | 
  'phone-alt' | 
  'circle-caret-left' | 
  'caret-circle-left' | 
  'square-chevron-up' | 
  'chevron-square-up' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'file-code' | 
  'shop' | 
  'store-alt' | 
  'floppy-disk' | 
  'save' | 
  'sort-up' | 
  'sort-asc' | 
  'hand-holding-dollar' | 
  'hand-holding-usd' | 
  'phone' | 
  'square-heart' | 
  'heart-square' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'arrow-left' | 
  'table-cells' | 
  'th' | 
  'messages-question' | 
  'comment' | 
  'envelope' | 
  'angles-up' | 
  'angle-double-up' | 
  'circle-info' | 
  'info-circle' | 
  'star-sharp-half-stroke' | 
  'star-sharp-half-alt' | 
  'truck' | 
  'crosshairs' | 
  'arrow-down-a-z' | 
  'sort-alpha-asc' | 
  'sort-alpha-down' | 
  'arrow-rotate-left' | 
  'arrow-left-rotate' | 
  'arrow-rotate-back' | 
  'arrow-rotate-backward' | 
  'undo' | 
  'calendar-plus' | 
  'minus' | 
  'subtract' | 
  'gear' | 
  'cog' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'keyboard' | 
  'caret-down' | 
  'piggy-bank' | 
  'sliders' | 
  'sliders-h' | 
  'map-pin' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'ticket' | 
  'download' | 
  'forward' | 
  'id-card' | 
  'drivers-license' | 
  'calendar-week' | 
  'rotate-right' | 
  'redo-alt' | 
  'rotate-forward' | 
  'truck-pickup' | 
  'upload' | 
  'bolt' | 
  'zap' | 
  'trash-undo' | 
  'trash-arrow-turn-left' | 
  'square-question' | 
  'question-square' | 
  'angle-down' | 
  'thumbs-down' | 
  'arrow-right-long' | 
  'long-arrow-right' | 
  'credit-card' | 
  'credit-card-alt' | 
  'bluetooth' | 
  'bell' | 
  'location-dot' | 
  'map-marker-alt' | 
  'file' | 
  'eraser' | 
  'earth-americas' | 
  'earth' | 
  'earth-america' | 
  'globe-americas' | 
  'star-half' | 
  'link' | 
  'chain' | 
  'magnifying-glass' | 
  'search' | 
  'chevrons-down' | 
  'chevron-double-down' | 
  'location-question' | 
  'map-marker-question' | 
  'receipt' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'square-chevron-right' | 
  'chevron-square-right' | 
  'truck-fast' | 
  'shipping-fast' | 
  'square-chevron-left' | 
  'chevron-square-left' | 
  'copy' | 
  'gun' | 
  'plus' | 
  'add' | 
  'expand' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'store' | 
  'chevron-left' | 
  'chevron-right' | 
  'location-check' | 
  'map-marker-check' | 
  'thumbtack' | 
  'thumb-tack' | 
  'spinner' | 
  'gears' | 
  'cogs' | 
  'circle-chevron-left' | 
  'chevron-circle-left' | 
  'bags-shopping' | 
  'calendar' | 
  'desktop' | 
  'desktop-alt' | 
  'book' | 
  'user-plus' | 
  'check' | 
  'earth-europe' | 
  'globe-europe' | 
  'chevrons-right' | 
  'chevron-double-right' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'circle-caret-right' | 
  'caret-circle-right' | 
  'circle-xmark' | 
  'times-circle' | 
  'xmark-circle' | 
  'gifts' | 
  'earth-asia' | 
  'globe-asia' | 
  'magnifying-glass-plus' | 
  'search-plus' | 
  'thumbs-up' | 
  'file-invoice' | 
  'magnifying-glass-minus' | 
  'search-minus' | 
  'print' | 
  'dollar-sign' | 
  'dollar' | 
  'usd' | 
  'users-gear' | 
  'users-cog' | 
  'barcode' | 
  'notdef' | 
  'circle-chevron-right' | 
  'chevron-circle-right' | 
  'trash-can' | 
  'trash-alt' | 
  'message' | 
  'comment-alt' | 
  'calendar-days' | 
  'calendar-alt' | 
  'sort-down' | 
  'sort-desc' | 
  'right-from-bracket' | 
  'sign-out-alt' | 
  'chevrons-up' | 
  'chevron-double-up' | 
  'angles-down' | 
  'angle-double-down' | 
  'location-plus' | 
  'map-marker-plus' | 
  'chevrons-left' | 
  'chevron-double-left' | 
  'circle-heart' | 
  'heart-circle' | 
  'address-book' | 
  'contact-book' | 
  'pencil' | 
  'pencil-alt' | 
  'backward' | 
  'caret-right' | 
  'user-check' | 
  'box-archive' | 
  'archive' | 
  'circle-caret-down' | 
  'caret-circle-down' | 
  'gift-card' | 
  'earth-africa' | 
  'globe-africa' | 
  'tablet-screen-button' | 
  'tablet-alt' | 
  'gavel' | 
  'legal' | 
  'bars' | 
  'navicon' | 
  'caret-left' | 
  'circle-exclamation' | 
  'exclamation-circle' | 
  'arrow-right-from-bracket' | 
  'sign-out' | 
  'circle-chevron-down' | 
  'chevron-circle-down' | 
  'compress' | 
  'asterisk' | 
  'square-check' | 
  'check-square' | 
  'list' | 
  'list-squares' | 
  'up-to-line' | 
  'arrow-alt-to-top' | 
  'lock' | 
  'pen-to-square' | 
  'edit' | 
  'bag-shopping' | 
  'shopping-bag' | 
  'arrow-down-z-a' | 
  'sort-alpha-desc' | 
  'sort-alpha-down-alt' | 
  'chevron-up' | 
  'stopwatch' | 
  'alarm-clock' | 
  'money-bill' | 
  'bookmark' | 
  'folder' | 
  'folder-blank' | 
  'file-waveform' | 
  'file-medical-alt' | 
  'user' | 
  'globe' | 
  'money-bill-wave' | 
  'star' | 
  'charging-station' | 
  'arrow-right-to-bracket' | 
  'sign-in' | 
  'server' | 
  'right-to-bracket' | 
  'sign-in-alt' | 
  'books' | 
  'user-group' | 
  'user-friends' | 
  'arrow-up-a-z' | 
  'sort-alpha-up' | 
  'play-pause' | 
  'square-chevron-down' | 
  'chevron-square-down' | 
  'comment-plus' | 
  'folder-open' | 
  'user-pen' | 
  'user-edit' | 
  'map-location-dot' | 
  'map-marked-alt' | 
  'gift' | 
  'square-plus' | 
  'plus-square' | 
  'caret-up' | 
  'minimize' | 
  'compress-arrows-alt' | 
  'circle-play' | 
  'play-circle' | 
  'circle-check' | 
  'check-circle' | 
  'marker' | 
  'circle-chevron-up' | 
  'chevron-circle-up' | 
  'pause' | 
  'address-card' | 
  'contact-card' | 
  'vcard' | 
  'circle-caret-up' | 
  'caret-circle-up' | 
  'circle-arrow-left' | 
  'arrow-circle-left' | 
  'envelope-open' | 
  'square' | 
  'down-to-line' | 
  'arrow-alt-to-bottom' | 
  'question' | 
  'money-check' | 
  'code' | 
  'location-pin' | 
  'map-marker' | 
  'arrow-right' | 
  'octagon-plus' | 
  'plus-octagon' | 
  'screwdriver-wrench' | 
  'tools' | 
  'heart' | 
  'mobile-screen-button' | 
  'mobile-alt' | 
  'circle-question' | 
  'question-circle' | 
  'phone-flip' | 
  'phone-alt' | 
  'circle-caret-left' | 
  'caret-circle-left' | 
  'square-chevron-up' | 
  'chevron-square-up' | 
  'basket-shopping' | 
  'shopping-basket' | 
  'eye' | 
  'file-code' | 
  'shop' | 
  'store-alt' | 
  'floppy-disk' | 
  'save' | 
  'sort-up' | 
  'sort-asc' | 
  'hand-holding-dollar' | 
  'hand-holding-usd' | 
  'phone' | 
  'square-heart' | 
  'heart-square' | 
  'user-gear' | 
  'user-cog' | 
  'trash' | 
  'arrow-left' | 
  'table-cells' | 
  'th' | 
  'messages-question' | 
  'comment' | 
  'envelope' | 
  'angles-up' | 
  'angle-double-up' | 
  'circle-info' | 
  'info-circle' | 
  'star-sharp-half-stroke' | 
  'star-sharp-half-alt' | 
  'truck' | 
  'crosshairs' | 
  'arrow-down-a-z' | 
  'sort-alpha-asc' | 
  'sort-alpha-down' | 
  'arrow-rotate-left' | 
  'arrow-left-rotate' | 
  'arrow-rotate-back' | 
  'arrow-rotate-backward' | 
  'undo' | 
  'calendar-plus' | 
  'minus' | 
  'subtract' | 
  'gear' | 
  'cog' | 
  'cart-shopping' | 
  'shopping-cart' | 
  'clock' | 
  'clock-four' | 
  'keyboard' | 
  'caret-down' | 
  'piggy-bank' | 
  'sliders' | 
  'sliders-h' | 
  'map-pin' | 
  'ellipsis-vertical' | 
  'ellipsis-v' | 
  'ticket' | 
  'download' | 
  'forward' | 
  'id-card' | 
  'drivers-license' | 
  'calendar-week' | 
  'rotate-right' | 
  'redo-alt' | 
  'rotate-forward' | 
  'truck-pickup' | 
  'upload' | 
  'bolt' | 
  'zap' | 
  'trash-undo' | 
  'trash-arrow-turn-left' | 
  'square-question' | 
  'question-square' | 
  'angle-down' | 
  'thumbs-down' | 
  'arrow-right-long' | 
  'long-arrow-right' | 
  'credit-card' | 
  'credit-card-alt' | 
  'bluetooth' | 
  'bell' | 
  'location-dot' | 
  'map-marker-alt' | 
  'file' | 
  'eraser' | 
  'earth-americas' | 
  'earth' | 
  'earth-america' | 
  'globe-americas' | 
  'star-half' | 
  'link' | 
  'chain' | 
  'magnifying-glass' | 
  'search' | 
  'chevrons-down' | 
  'chevron-double-down' | 
  'location-question' | 
  'map-marker-question' | 
  'receipt' | 
  'chevron-down' | 
  'list-ul' | 
  'list-dots' | 
  'circle-user' | 
  'user-circle' | 
  'square-chevron-right' | 
  'chevron-square-right' | 
  'truck-fast' | 
  'shipping-fast' | 
  'square-chevron-left' | 
  'chevron-square-left' | 
  'copy' | 
  'gun' | 
  'plus' | 
  'add' | 
  'expand' | 
  'xmark' | 
  'close' | 
  'multiply' | 
  'remove' | 
  'times' | 
  'store' | 
  'chevron-left' | 
  'chevron-right' | 
  'location-check' | 
  'map-marker-check' | 
  'thumbtack' | 
  'thumb-tack' | 
  'spinner' | 
  'gears' | 
  'cogs' | 
  'circle-chevron-left' | 
  'chevron-circle-left' | 
  'bags-shopping' | 
  'calendar' | 
  'desktop' | 
  'desktop-alt' | 
  'book' | 
  'user-plus' | 
  'check' | 
  'earth-europe' | 
  'globe-europe' | 
  'chevrons-right' | 
  'chevron-double-right' | 
  'triangle-exclamation' | 
  'exclamation-triangle' | 
  'warning' | 
  'paper-plane' | 
  'circle-caret-right' | 
  'caret-circle-right' | 
  'circle-xmark' | 
  'times-circle' | 
  'xmark-circle' | 
  'gifts' | 
  'earth-asia' | 
  'globe-asia' | 
  'magnifying-glass-plus' | 
  'search-plus' | 
  'thumbs-up' | 
  'file-invoice' | 
  'magnifying-glass-minus' | 
  'search-minus' | 
  'print' | 
  'dollar-sign' | 
  'dollar' | 
  'usd' | 
  'users-gear' | 
  'users-cog' | 
  'barcode' | 
  'notdef';
